# run: conda env create --file environment.yml
name: hack_2022_ecmwf_fluttering
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - ipython>=7.30
  - ipykernel>=6.4
  - jupyter>=1.0
  # Data download API
  - cdsapi>=0.5

  - numpy>=1.22
  - xarray>=0.21
  - pandas>=1.3
  # Xarray voluntary dependencies
  - dask
  - netCDF4
  - bottleneck
  - cfgrib

  - pip

  # plotting
  - cartopy>=0.18
  - matplotlib>=3.5
  - seaborn>=0.11
  
  # animation VS Code
  - ipympl>=0.9
  
